name: Check, tag and merge

on:
  pull_request:
    types: [labeled, synchronize, reopened]

jobs:
  auto-check-tag-merge:
    if: contains(github.event.pull_request.labels.*.name, 'autotag')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for diff comparisons
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install GitPython
        run: pip install gitpython

      - name: Run version merge & tag script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: python scripts/check-tag-and-merge.py ${{ github.event.pull_request.number }}

      # - name: automerge
      #   uses: "pascalgn/automerge-action@v0.16.4"
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
